import "@hotwired/turbo-rails"

import "modules/comment_edit"
import "modules/favorite_author"
import "modules/flash"
import "modules/modal_author_delete"
import "modules/modal_book_delete"
import "modules/modal_register"
import "modules/published_date"
import "modules/reading_status"
import "modules/search_box"